### ISSUE TITLE
top bar not completely fixed 

### ISSUE THREAD

**Issue by ad3429** [Noemi842/prj-rev-bwfs-tea-cozy#3]
https://github.com/Noemi842/prj-rev-bwfs-tea-cozy/blob/master/teacozy/index.html#L10-L19

The top header bar does not seem to be completely fixed to the top of the screen. When I scroll down the page, there is a small strip at the top of the bar that is open and I can see what is behind it. This should be a simple CSS fix so I would recommend going back to fix that.

**Comment by Noemi842** [comment]
fixed now. 
  top: 0px;
